# Stateless
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: itchybitchyspider
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: ibs-nginx
        image: eu.gcr.io/webber-takken/ibs-nginx
#        resources:
#          requests:
#            cpu: 100m
#            memory: 100Mi
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: itchybitchyspider
  labels:
    app: nginx
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    app: nginx
    tier: frontend
