version: "2"
services:
  mariadb:
    build: .k8s/images/base/mariadb
    image: base-mariadb
  php:
    build: .k8s/images/base/php-fpm
    image: base-php-fpm
  nginx:
    build: .k8s/images/base/nginx
    image: base-nginx
  elk:
    build: .k8s/images/base/elk
    image: base-elk
