version: '2'
services:
    db:
        build: .docker/mariadb
        image: eu.gcr.io/webber-takken/ibs-mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: .docker/php-fpm
        image: eu.gcr.io/webber-takken/ibs-php
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        links:
            - db
    nginx:
        build: .docker/nginx
        image: eu.gcr.io/webber-takken/ibs-nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - .docker/elk/logstash:/etc/logstash:cached
            - .docker/elk/logstash/patterns:/opt/logstash/patterns:cached
        volumes_from:
            - php
            - nginx
