version: "2"
services:
  mariadb-prod:
    build: .k8s/images/base/mariadb
    image: <your-container-registry>/mariadb
  php-prod:
    build: .k8s/images/prod/php-fpm
    image: <your-container-registry>/php-fpm
  nginx-prod:
    build: .k8s/images/prod/nginx
    image: <your-container-registry>/nginx
  elk-prod:
    build: .k8s/images/base/elk
    image: <your-container-registry>/elk
