version: '2'
services:
  mariadb-prod:
    build: .k8s/images/base/mariadb
    image: eu.gcr.io/webber-takken/ibs-mariadb
  php-fpm-prod:
    build: .k8s/images/prod/php-fpm
    image: eu.gcr.io/webber-takken/ibs-php-fpm
  nginx-prod:
    build: .k8s/images/prod/nginx
    image: eu.gcr.io/webber-takken/ibs-nginx
  elk-prod:
    build: .k8s/images/base/elk
    image: eu.gcr.io/webber-takken/ibs-elk
