version: '2'
services:
    db:
        build: .k8s/images/base/mariadb
        image: ibs-mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: .k8s/images/dev/php-fpm
        image: ibs-php
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/app:cached
            - ./logs/symfony:/var/www/app/var/log:cached
        links:
            - db
    nginx:
        build: .k8s/images/dev/nginx
        image: ibs-nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
    elk:
        build: .k8s/images/base/elk
        image: ibs-elk
        ports:
            - "81:80"
        volumes_from:
            - php
            - nginx
