version: '2'
services:
    db:
        build: .docker/mariadb
        image: itchybitchyspider.azurecr.io/ibs-mariadb:v1
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: .docker/php-fpm
        image: itchybitchyspider.azurecr.io/ibs-php:v1
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        links:
            - db
    nginx:
        build: .docker/nginx
        image: itchybitchyspider.azurecr.io/ibs-nginx:v1
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
        labels:
            kompose.service.type: loadbalancer
            kompose.service.expose: "true"
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - .docker/elk/logstash:/etc/logstash:cached
            - .docker/elk/logstash/patterns:/opt/logstash/patterns:cached
        volumes_from:
            - php
            - nginx
