---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: spider-wtf
  namespace: itchybitchyspider
spec:
  secretName: spider-wtf-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: spider.wtf
  dnsNames:
  - www.spider.wtf
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - spider.wtf
      - www.spider.wtf
