apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: itchybitchyspider
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: www.spider.wtf
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
        - www.spider.wtf
      secretName: spider-wtf-certificate
