---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  namespace: itchybitchyspider
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
