# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Install testing dependencies (no prod packages here)
      - run:
          name: Installing Test Dependencies
          command: |
            sudo apt install -y zlib1g-dev
            sudo docker-php-ext-install zip

      # Install application dependencies
      - restore_cache:
          keys:
          - composer-deps-{{ checksum "composer.lock" }}
          - composer-deps-

      - restore_cache:
          keys:
          - yarn-deps-{{ checksum "yarn.lock" }}
          - yarn-deps-

      - run:
          name: Installing application (part 1)
          command: |
            sudo composer self-update
            composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: composer-deps-{{ checksum "composer.lock" }}

      - run:
          name: Installing application (part 2)
          command: |
            yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: yarn-deps-{{ checksum "yarn.lock" }}

      # run tests!
      - run:
          name: Testing application
          command: |
            vendor/bin/simple-phpunit
