---
- name: Update composer
  composer:
    command: self-update
    working_dir: "{{ ansistrano_release_path.stdout }}"

- name: Install composer dependencies
  composer:
    command: install
    working_dir: "{{ ansistrano_release_path.stdout }}"

- name: Clear the cache
  command: "{{ release_console_path }} cache:clear --env=prod"

- name: Warmup the cache
  command: "{{ release_console_path }} cache:warmup --env=prod"
