---
- name: COMPOSER | Update composer
  composer:
    command: self-update
    working_dir: "{{ ansistrano_release_path.stdout }}"

- name: COMPOSER | Install dependencies & run scripts
  composer:
    command: install
    working_dir: "{{ ansistrano_release_path.stdout }}"

# This would be for making sure they run in --env=prod
#- name: Clear the cache
#  command: "{{ release_console_path }} cache:clear --env=prod"
#  become: true
#
#- name: Warmup the cache
#  command: "{{ release_console_path }} cache:warmup --env=prod"
#  become: true
