# Stateless
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
spec:
  selector:
    matchLabels:
      app: php-fpm
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: php-fpm
        tier: backend
    spec:
      containers:
      - name: php
        image: <your-container-registry>/php-fpm
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    app: php-fpm
    tier: backend
spec:
  ports:
  - name: php
    port: 9000
    targetPort: 9000
  - name: fast-cgi-listener
    port: 9001
    targetPort: 9001
  selector:
    app: php-fpm
    tier: backend
